spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/zmovie?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456





logging:
  level:
    root: info
    com.zmovie: debug
  file:
    name: log/zmovie.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  base:
    enable:fasle


